# @author agalue@opennms.com
---
- name: Start Cassandra in sequence
  hosts: cassandra
  become: true
  order: sorted
  serial: 1
  tasks:
  - name: Start Cassandra in sequence
    loop: '{{ instances | dict2items }}'
    include_tasks: 'playbook-start-cassandra.yaml'

- name: Start OpenNMS
  hosts: opennms
  become: true
  tasks:
  - name: 'Start processes'
    systemd:
      name: 'opennms'
      state: started
