# @author agalue@opennms.com
---
- name: Start Cassandra in sequence
  hosts: cassandra
  become: true
  order: sorted
  serial: 1
  tasks:
  - name: Start Cassandra in sequence
    loop: '{{ instances | dict2items }}'
    include_tasks: 'tasks-start-cassandra.yaml'
