# @author agalue@opennms.com
---
- name: Enable Network Topology
  hosts: cassandra
  become: true
  order: sorted
  tasks:

  - name: Set concurrent_compactors
    replace:
      path: '/etc/cassandra/{{ item.key }}/cassandra.yaml'
      regexp: '^.*(concurrent_compactors:).*'
      replace: '\1 {{ ansible_processor_cores }}'
    loop: '{{ instances | dict2items }}'

  - name: Set compaction_throughput_mb_per_sec
    replace:
      path: '/etc/cassandra/{{ item.key }}/cassandra.yaml'
      regexp: '^.*(compaction_throughput_mb_per_sec:).*'
      replace: '\1 {{ compaction_throughput }}'
    loop: '{{ instances | dict2items }}'

  - name: Set stream_throughput_outbound_megabits_per_sec
    replace:
      path: '/etc/cassandra/{{ item.key }}/cassandra.yaml'
      regexp: '^.*(stream_throughput_outbound_megabits_per_sec:).*'
      replace: '\1 {{ stream_throughput }}'
    loop: '{{ instances | dict2items }}'

  - name: Update snitch
    replace:
      path: '/etc/cassandra/{{ item.key }}/cassandra.yaml'
      regexp: '^.*(endpoint_snitch:).*'
      replace: '\1 GossipingPropertyFileSnitch'
    loop: '{{ instances | dict2items }}'

  - name: Force default cassandra-rackdc.properties
    template:
      src: cassandra-rackdc-fixed.j2
      dest: '/etc/cassandra/{{ item.key }}/cassandra-rackdc.properties'
      mode: 0644
      owner: cassandra
      group: cassandra
    loop: '{{ instances | dict2items }}'

  - name: Remove cassandra-topology.properties
    file:
      path: '/etc/cassandra/{{ item.key }}/cassandra-topology.properties'
      state: absent
    loop: '{{ instances | dict2items }}'
